<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="AI\" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="dotenv.net" Version="4.0.2" />
      <PackageReference Include="VkNet" Version="1.79.0-alpha-138" />
    </ItemGroup>

</Project>
